/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WsPlaygroundRouteImport } from './routes/ws-playground'
import { Route as IndexRouteImport } from './routes/index'

const WsPlaygroundRoute = WsPlaygroundRouteImport.update({
  id: '/ws-playground',
  path: '/ws-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ws-playground': typeof WsPlaygroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ws-playground': typeof WsPlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ws-playground': typeof WsPlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ws-playground'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ws-playground'
  id: '__root__' | '/' | '/ws-playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WsPlaygroundRoute: typeof WsPlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ws-playground': {
      id: '/ws-playground'
      path: '/ws-playground'
      fullPath: '/ws-playground'
      preLoaderRoute: typeof WsPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WsPlaygroundRoute: WsPlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
